export const MNG_BUS_TIMINGS = [
  { title: 'Navadurga Prasad', hour: 7, minute: 0, day: 'am' },
  { title: 'Padmambikaa', hour: 7, minute: 25, day: 'am' },
  { title: 'Vishal', hour: 8, minute: 10, day: 'am' },
  { title: 'Vishal', hour: 8, minute: 46, day: 'am' },
  { title: 'Navadurga Prasad', hour: 9, minute: 30, day: 'am' },
  { title: 'Vishal', hour: 9, minute: 45, day: 'am' },
  { title: 'Vishal', hour: 9, minute: 58, day: 'am' },
  { title: 'Laxmi Prasad', hour: 10, minute: 5, day: 'am' },
  { title: 'Reshma', hour: 10, minute: 26, day: 'am' },
  { title: 'Padmambikaa', hour: 11, minute: 0, day: 'am' },
  { title: 'Christa Kiran', hour: 11, minute: 20, day: 'am' },
  { title: 'Vishal', hour: 11, minute: 30, day: 'am' },
  { title: 'Padmambikaa', hour: 11, minute: 51, day: 'am' },
  { title: 'Navadurga Prasad', hour: 12, minute: 0, day: 'pm' },
  { title: 'Rajarajeshwari', hour: 12, minute: 9, day: 'pm' },
  { title: 'Shree Annapoorneshwari', hour: 12, minute: 9, day: 'pm' },
  { title: 'Vishal', hour: 12, minute: 25, day: 'pm' },
  { title: 'Navadurga Prasad', hour: 12, minute: 38, day: 'pm' },
  { title: 'Vishal', hour: 12, minute: 35, day: 'pm' },
  { title: 'Padmambikaa', hour: 12, minute: 51, day: 'pm' },
  { title: 'Rajarajeshwari', hour: 12, minute: 56, day: 'pm' },
  { title: 'Navadurga Prasad', hour: 1, minute: 10, day: 'pm' },
  { title: 'Vishal', hour: 1, minute: 32, day: 'pm' },
  { title: 'Vishal', hour: 2, minute: 0, day: 'pm' },
  { title: 'Laxmi Ganesh', hour: 2, minute: 17, day: 'pm' },
  { title: 'Padmambikaa', hour: 2, minute: 37, day: 'pm' },
  { title: 'Navadurga Prasad', hour: 2, minute: 44, day: 'pm' },
  { title: 'Padmambikaa', hour: 2, minute: 57, day: 'pm' },
  { title: 'Reshma', hour: 3, minute: 5, day: 'pm' },
  { title: 'Vishal', hour: 3, minute: 21, day: 'pm' },
  { title: 'Padmambikaa', hour: 3, minute: 59, day: 'pm' },
  { title: 'Ayra', hour: 4, minute: 10, day: 'pm' },
  { title: 'Vishal', hour: 4, minute: 19, day: 'pm' },
  { title: 'Vishal', hour: 4, minute: 29, day: 'pm' },
  { title: 'Vishal', hour: 4, minute: 41, day: 'pm' },
  { title: 'Vishal', hour: 4, minute: 56, day: 'pm' },
  { title: 'Mercy', hour: 5, minute: 2, day: 'pm' },
  { title: 'Navadurga Prasad', hour: 5, minute: 7, day: 'pm' },
  { title: 'Navadurga Prasad', hour: 5, minute: 22, day: 'pm' },
]

export const UDP_BUS_TIMINGS = [
  { title: 'Ayra', hour: 8, minute: 13, day: 'AM' },
  { title: 'Sahil', hour: 8, minute: 19, day: 'AM' },
  { title: 'Christa Jyothi', hour: 9, minute: 54, day: 'AM' },
  { title: 'Decent', hour: 9, minute: 59, day: 'AM' },
  { title: 'Christa Jyothi', hour: 10, minute: 23, day: 'AM' },
  { title: 'Sangam', hour: 10, minute: 36, day: 'AM' },
  { title: 'Naveen', hour: 11, minute: 26, day: 'AM' },
  { title: 'Naveen', hour: 11, minute: 28, day: 'AM' },
  { title: 'Naveen', hour: 11, minute: 33, day: 'AM' },
  { title: 'Rashmi Travels', hour: 11, minute: 44, day: 'AM' },
  { title: 'Naveen', hour: 12, minute: 18, day: 'PM' },
  { title: 'Shree Padma', hour: 12, minute: 38, day: 'PM' },
  { title: 'Shahil', hour: 12, minute: 52, day: 'PM' },
  { title: 'Kanthi', hour: 13, minute: 30, day: 'PM' },
  { title: 'Kanthi', hour: 13, minute: 43, day: 'PM' },
  { title: 'Bharathi', hour: 13, minute: 51, day: 'PM' },
  { title: 'Sangam', hour: 14, minute: 6, day: 'PM' },
  { title: 'Christa Jyothi', hour: 15, minute: 12, day: 'PM' },
  { title: 'Naveen', hour: 15, minute: 45, day: 'PM' },
  { title: 'Naveen', hour: 16, minute: 25, day: 'PM' },
  { title: 'Shree Padma', hour: 16, minute: 49, day: 'PM' },
  { title: 'Shree Padma', hour: 17, minute: 21, day: 'PM' },
]
