export const MNG_BUS_TIMINGS = [
    {name: "Navadurga Prasad", hour: 7, minute: 0},
    {name: "Padmambikaa", hour: 7, minute: 25}, 
    {name: "Vishal", hour: 8, minute: 10}, 
    {name: "Vishal", hour: 8, minute: 46}, 
    {name: "Navadurga Prasad", hour: 9, minute: 30}, 
    {name: "Vishal", hour: 9, minute: 45}, 
    {name: "Vishal", hour: 9, minute: 58}, 
    {name: "Laxmi Prasad", hour: 10, minute: 5}, 
    {name: "Reshma", hour: 10, minute: 26}, 
    {name: "Padmambikaa", hour: 11, minute: 0}, 
    {name: "Christa Kiran", hour: 11, minute: 20}, 
    {name: "Vishal", hour: 11, minute: 30}, 
    {name: "Padmambikaa", hour: 11, minute: 51}, 
    {name: "Navadurga Prasad", hour: 12, minute: 0}, 
    {name: "Rajarajeshwari", hour: 12, minute: 9}, 
    {name: "Shree Annapoorneshwari", hour: 12, minute: 9}, 
    {name: "Vishal", hour: 12, minute: 25}, 
    {name: "Navadurga Prasad", hour: 12, minute: 38}, 
    {name: "Vishal", hour: 12, minute: 35}, 
    {name: "Padmambikaa", hour: 12, minute: 51}, 
    {name: "Rajarajeshwari", hour: 12, minute: 56}, 
    {name: "Navadurga Prasad", hour: 13, minute: 10},
    {name: "Vishal", hour: 13, minute: 32},
    {name: "Vishal", hour: 14, minute: 0}, 
    {name: "Laxmi Ganesh", hour: 14, minute: 17},
    {name: "Padmambikaa", hour: 14, minute: 37},
    {name: "Navadurga Prasad", hour: 14, minute: 44},
    {name: "Padmambikaa", hour: 14, minute: 57},
    {name: "Reshma", hour: 15, minute: 5},
    {name: "Vishal", hour: 15, minute: 21},
    {name: "Padmambikaa", hour: 15, minute: 59},
    {name: "Ayra", hour: 16, minute: 10},
    {name: "Vishal", hour: 16, minute: 19},
    {name: "Vishal", hour: 16, minute: 29},
    {name: "Vishal", hour: 16, minute: 41},
    {name: "Vishal", hour: 16, minute: 56},
    {name: "Mercy", hour: 17, minute: 2},
    {name: "Navadurga Prasad", hour: 17, minute: 7},
    {name: "Navadurga Prasad", hour: 17, minute: 22}
    ];

export const UDP_BUS_TIMINGS = [
    {name: "Ayra", hour: 8, minute: 13},
    {name: "Sahil", hour: 8, minute: 19},
    {name: "Christa Jyothi", hour: 9, minute: 54},
    {name: "Decent", hour: 9, minute: 59},
    {name: "Christa Jyothi", hour: 10, minute: 23},
    {name: "Sangam", hour: 10, minute: 36},
    {name: "Naveen", hour: 11, minute: 26},
    {name: "Naveen", hour: 11, minute: 28},
    {name: "Naveen", hour: 11, minute: 33},
    {name: "Rashmi Travels", hour: 11, minute: 44},
    {name: "Naveen", hour: 12, minute: 18},
    {name: "Shree Padma", hour: 12, minute: 38},
    {name: "Shahil", hour: 12, minute: 52},
    {name: "Kanthi", hour: 13, minute: 30},
    {name: "Kanthi", hour: 13, minute: 43},
    {name: "Bharathi", hour: 13, minute: 51},
    {name: "Sangam", hour: 14, minute: 6},
    {name: "Christa Jyothi", hour: 15, minute: 12},
    {name: "Naveen", hour: 15, minute: 45},
    {name: "Naveen", hour: 16, minute: 25},
    {name: "Shree Padma", hour: 16, minute: 49},
    {name: "Shree Padma", hour: 17, minute: 21}
];