export const MNG_BUS_TIMINGS = [
  { name: 'Navadurga Prasad', hour: 7, minute: 0, period: 'am' },
  { name: 'Padmambikaa', hour: 7, minute: 25, period: 'am' },
  { name: 'Vishal', hour: 8, minute: 10, period: 'am' },
  { name: 'Vishal', hour: 8, minute: 46, period: 'am' },
  { name: 'Navadurga Prasad', hour: 9, minute: 30, period: 'am' },
  { name: 'Vishal', hour: 9, minute: 45, period: 'am' },
  { name: 'Vishal', hour: 9, minute: 58, period: 'am' },
  { name: 'Laxmi Prasad', hour: 10, minute: 5, period: 'am' },
  { name: 'Reshma', hour: 10, minute: 26, period: 'am' },
  { name: 'Padmambikaa', hour: 11, minute: 0, period: 'am' },
  { name: 'Christa Kiran', hour: 11, minute: 20, period: 'am' },
  { name: 'Vishal', hour: 11, minute: 30, period: 'am' },
  { name: 'Padmambikaa', hour: 11, minute: 51, period: 'am' },
  { name: 'Navadurga Prasad', hour: 12, minute: 0, period: 'pm' },
  { name: 'Rajarajeshwari', hour: 12, minute: 9, period: 'pm' },
  { name: 'Shree Annapoorneshwari', hour: 12, minute: 9, period: 'pm' },
  { name: 'Vishal', hour: 12, minute: 25, period: 'pm' },
  { name: 'Navadurga Prasad', hour: 12, minute: 38, period: 'pm' },
  { name: 'Vishal', hour: 12, minute: 35, period: 'pm' },
  { name: 'Padmambikaa', hour: 12, minute: 51, period: 'pm' },
  { name: 'Rajarajeshwari', hour: 12, minute: 56, period: 'pm' },
  { name: 'Navadurga Prasad', hour: 1, minute: 10, period: 'pm' },
  { name: 'Vishal', hour: 1, minute: 32, period: 'pm' },
  { name: 'Vishal', hour: 2, minute: 0, period: 'pm' },
  { name: 'Laxmi Ganesh', hour: 2, minute: 17, period: 'pm' },
  { name: 'Padmambikaa', hour: 2, minute: 37, period: 'pm' },
  { name: 'Navadurga Prasad', hour: 2, minute: 44, period: 'pm' },
  { name: 'Padmambikaa', hour: 2, minute: 57, period: 'pm' },
  { name: 'Reshma', hour: 3, minute: 5, period: 'pm' },
  { name: 'Vishal', hour: 3, minute: 21, period: 'pm' },
  { name: 'Padmambikaa', hour: 3, minute: 59, period: 'pm' },
  { name: 'Ayra', hour: 4, minute: 10, period: 'pm' },
  { name: 'Vishal', hour: 4, minute: 19, period: 'pm' },
  { name: 'Vishal', hour: 4, minute: 29, period: 'pm' },
  { name: 'Vishal', hour: 4, minute: 41, period: 'pm' },
  { name: 'Vishal', hour: 4, minute: 56, period: 'pm' },
  { name: 'Mercy', hour: 5, minute: 2, period: 'pm' },
  { name: 'Navadurga Prasad', hour: 5, minute: 7, period: 'pm' },
  { name: 'Navadurga Prasad', hour: 5, minute: 22, period: 'pm' },
]

export const UDP_BUS_TIMINGS = [
  { name: 'Ayra', hour: 8, minute: 13, period: 'AM' },
  { name: 'Sahil', hour: 8, minute: 19, period: 'AM' },
  { name: 'Christa Jyothi', hour: 9, minute: 54, period: 'AM' },
  { name: 'Decent', hour: 9, minute: 59, period: 'AM' },
  { name: 'Christa Jyothi', hour: 10, minute: 23, period: 'AM' },
  { name: 'Sangam', hour: 10, minute: 36, period: 'AM' },
  { name: 'Naveen', hour: 11, minute: 26, period: 'AM' },
  { name: 'Naveen', hour: 11, minute: 28, period: 'AM' },
  { name: 'Naveen', hour: 11, minute: 33, period: 'AM' },
  { name: 'Rashmi Travels', hour: 11, minute: 44, period: 'AM' },
  { name: 'Naveen', hour: 12, minute: 18, period: 'PM' },
  { name: 'Shree Padma', hour: 12, minute: 38, period: 'PM' },
  { name: 'Shahil', hour: 12, minute: 52, period: 'PM' },
  { name: 'Kanthi', hour: 13, minute: 30, period: 'PM' },
  { name: 'Kanthi', hour: 13, minute: 43, period: 'PM' },
  { name: 'Bharathi', hour: 13, minute: 51, period: 'PM' },
  { name: 'Sangam', hour: 14, minute: 6, period: 'PM' },
  { name: 'Christa Jyothi', hour: 15, minute: 12, period: 'PM' },
  { name: 'Naveen', hour: 15, minute: 45, period: 'PM' },
  { name: 'Naveen', hour: 16, minute: 25, period: 'PM' },
  { name: 'Shree Padma', hour: 16, minute: 49, period: 'PM' },
  { name: 'Shree Padma', hour: 17, minute: 21, period: 'PM' },
]
