import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar'
import Provider from '@/components/SessionProvider'
import '@/styles/globals.css'

import { Inter } from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Provider>
        <body className={`font-sans ${inter.variable}`}>
          <Navbar />
          {children}
          <Footer/>
        </body>
      </Provider>
    </html>
  )
}
